恢复开始的配置删除调试命令

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -11,7 +11,7 @@ on:
 
 env:
   IDF_PATH: /opt/esp/idf
-  test_dirs: components/button/test_apps
+  test_dirs: .
 
 defaults:
   run:
@@ -40,34 +40,32 @@ jobs:
       - name: Build Test Application with ESP-IDF
         run: |
           . $IDF_PATH/export.sh
-          echo "Starting build process..."
           idf-build-apps build \
             -p ${{ env.test_dirs }} \
             --target ${{ matrix.target }} \
             --recursive \
-            --build-dir build_${{ matrix.target }}_${{ matrix.idf-branch }} > build_output.log 2>&1
-      - name: Output build log
+            --build-dir build_${{ matrix.target }}_${{ matrix.idf-branch }}
+      - name: List the files in the build directory
+        run: ls build_${{ matrix.target }}_${{ matrix.idf-branch }}
+      - name: Check if sdkconfig.json exists
         run: |
-          echo "Build output log:"
-          cat build_output.log
-      - name: List all files in the current directory
-        run: |
-          echo "Listing all files in the current directory:"
-          find . -type f -print
-      - name: List build directory
-        run: |
-          echo "Listing build directory for target ${{ matrix.target }} and branch ${{ matrix.idf-branch }}"
-          ls -R build_${{ matrix.target }}_${{ matrix.idf-branch }}
+          if [ -f build_${{ matrix.target }}_${{ matrix.idf-branch }}/config/sdkconfig.json ]; then
+            echo "sdkconfig.json found"
+            cat build_${{ matrix.target }}_${{ matrix.idf-branch }}/config/sdkconfig.json
+          else
+            echo "sdkconfig.json not found"
+            exit 1
+          fi
       - name: Upload files to artifacts for run-target job
         uses: actions/upload-artifact@v3
         with:
           name: built_binaries_${{ matrix.target }}_${{ matrix.idf-branch }}
           path: |
-            build_${{ matrix.target }}_${{ matrix.idf-branch }}/bootloader/bootloader.bin
-            build_${{ matrix.target }}_${{ matrix.idf-branch }}/partition_table/partition-table.bin
-            build_${{ matrix.target }}_${{ matrix.idf-branch }}/*.bin
-            build_${{ matrix.target }}_${{ matrix.idf-branch }}/*.elf
-            build_${{ matrix.target }}_${{ matrix.idf-branch }}/flasher_args.json
+            **/build**/bootloader/bootloader.bin
+            **/build**/partition_table/partition-table.bin
+            **/build**/*.bin
+            **/build**/*.elf
+            **/build**/flasher_args.json
           if-no-files-found: error
 
   simulate-test:
@@ -88,13 +86,13 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.9'
+          python-version: '3.9'  # Ensure this matches the Python version needed for your testing
       - name: Download built binaries from build job
         uses: actions/download-artifact@v3
         with:
           name: built_binaries_${{ matrix.target }}_${{ matrix.idf-branch }}
       - name: Install Python packages for PyTest
-        run: pip install -r tools/requirements/requirement.pytest.txt
+        run: pip install -r requirements.txt
       - name: Set Wokwi Token (GitHub environment secret `WOKWI_CLI_TOKEN`)
         run: echo "WOKWI_CLI_TOKEN=${{ secrets.WOKWI_CLI_TOKEN }}" >> $GITHUB_ENV
       - name: Run Test App in WokWi Simulator
